DROP DATABASE IF EXISTS Employee_Tracker;
CREATE DATABASE Employee_Tracker;
USE Employee_Tracker;



CREATE TABLE departrment(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE role(
id INT PRIMARY KEY,
title VARCHAR(30) UNIQUE NOT NULL,
salary DECIMAL UNSIGNED NOT NULL,
department_id INT UNSIGNED NOT NULL
)

CREATE TABLE Employee(
id INT PRIMARY KEY,
first_name VARCHAR(30) UNIQUE NOT NULL,
last_name VARCHAR(30) UNIQUE NOT NULL,
role_id INT UNSIGNED NOT NULL,
manager_id INT UNSIGNED 

)